# Generated by Django 5.2.5 on 2025-08-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('debit', models.FloatField(blank=True, null=True)),
                ('credit', models.FloatField(blank=True, null=True)),
                ('sub_category', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('category_type', models.CharField(max_length=50)),
                ('month_number', models.IntegerField()),
                ('weekday', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
