# Generated by Django 5.2.5 on 2025-08-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Charity', 'Charity'), ('Dining Out', 'Dining Out'), ('Discretionary', 'Discretionary'), ('Living Expenses', 'Living Expenses'), ('Medical', 'Medical'), ('Passive', 'Passive'), ('Salary', 'Salary'), ('Transport', 'Transport')], max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='month_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='weekday',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
